---

# HTTP
http_url: "http://localhost:8401/"
package_name: "net.es.nsi.dds"
static_path: "config/www/"
www_path: "/www"

# DDS

# Authorization
read_access: "CN=nsi-aggr-west.es.net,OU=Domain Control Validated"
write_access: "CN=nsi-aggr-west.es.net,OU=Domain Control Validated"
write_nsa_id_1: "urn:ogf:network:es.net:2014:nsa:nsi-aggr-west"
admin_access: "CN=nsi-aggr-west.es.net,OU=Domain Control Validated"
peer_access: "CN=nsi-aggr-west.es.net,OU=Domain Control Validated"
access_control_enabled: "true"
peer_nsa_id_1: "urn:ogf:network:es.net:2014:nsa:nsi-aggr-west"
peer_nsa_id_2: "urn:ogf:network:es.net:2014:nsa:nsi-aggr-west"

# Logging
logging: "PathToLogFile"

# TLS
trust_store: "TRUSTSTORE"
trust_store_password: "PASSWORD"
key_store: "KEYSTORE"
key_store_password: "PASSWORD"