---
# Configuration
- name: Create symlink
  file: 
    src: "{{ config_path }}/{{ opennsa_service }}"
    dest: /etc/systemd/system/opennsa.service
    state: link 
    owner: root
    group: root
  notify: 
    - Reload daemon
  tags: [ configuration ]

- name: Start opennsa service
  shell: systemctl start opennsa.service
  tags: [ configuration ]