---
- include_tasks: tasks/setup.yml
  tags: [ setup, prerequisites, app_user, download_repos ]

- include_tasks: tasks/venv_setup.yml
  tags: [ virtualenv ]

- include_tasks: tasks/ssl_setup.yml
  tags: [ ssl ]

- include_tasks: tasks/configuration.yml
  tags: [ configuration ]

- include_tasks: tasks/postgresql.yml
  tags: [ postgresql ]
