--- 
  - hosts: test_servers
    become: true
    vars_files:
      - vars/general.yml
      - vars/passwords.yml
      - vars/config.yml

    tasks:
      - include_tasks: tasks/prerequisites_setup.yml
        tags: [ prerequisites ]

      - include_tasks: tasks/create_user.yml
        tags: [ app_user ]

      - include_tasks: tasks/download_repos.yml
        tags: [ repos ]

      - include_tasks: tasks/venv_setup.yml
        tags: [ virtualenv ]

      - include_tasks: tasks/configuration.yml
        tags: [ configuration ]

      - include_tasks: tasks/postgresql.yml
        tags: [ PostgreSQL ]

      - include_tasks: tasks/ssl_setup.yml
        tags: [ SSL ]
      
    handlers:
      - name: Restart PostgreSQL
        service: 
          name: postgresql 
          state: restarted
        tags: [ PostgreSQL ]
      

      

      

      

      

      

      
