--- 
  - hosts: test_servers
    become: true
    vars_files:
      - vars/general.yml
      - vars/passwords.yml
      - vars/config.yml

    tasks:
      # Setup package manager
      - name: Install aptitude
        apt: 
          name: aptitude
          update_cache: yes 
          state: latest
        tags: [ setup ]

      - name: Add sbt apt key
        apt_key:
          url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823"
          state: present
        tags: [ sbt, setup ]

      - name: Add sbt apt repository
        apt_repository:
          repo: "deb https://repo.scala-sbt.org/scalasbt/debian all main"
          state: present
          filename: sbt
          update_cache: yes
        tags: [ sbt, setup ]  
      
      # Install prerequisites
      - name: Install prerequisites
        apt:
          name: "{{ item }}"
          update_cache: yes
          state: latest
        loop: "{{ prerequisites }}"
        tags: [ sbt, java, apache2, setup ]

      # Change java version
      - name: Change java version
        alternatives:
          name: java
          path: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java
        tags: [ java, setup ]

      # Enable apache2 modules
      - name: Enable apache2 modules
        community.general.apache2_module:
          state: present
          name: "{{ item }}"
        loop: "{{ apache2_modules }}"
        tags: [ apache2, setup ]

      # Create app specific user
      - name: Create a user
        user: 
          name: "{{ app_user }}"
          password: "{{ user_password }}"                              
          state: present
          createhome: yes
          home: "{{ home_path }}"
          shell: /bin/bash
        tags: [ user, setup ]

      # Download repos
      - name: Download the nsi-dds, nsi-safnari, nsi-pce and opennsa3
        git:
          repo: "{{ item.repository }}"
          dest: "{{ home_path }}/{{ item.name }}"
          force: yes
        loop: "{{ packages }}"
        tags: [ repo, setup ]

      - name: Change ownership
        file:
          path: "{{ home_path }}"
          state: directory
          owner: "{{ app_user }}"
          group: "{{ app_user }}"
          recurse: yes
        tags: [ repo, setup ]

    handlers:
      - name: Restart Apache
        service:
          name: apache2
          state: restarted
      tags: [ apache2, setup ]

      - name: Restart PostgreSQL
        service: 
          name: postgresql 
          state: restarted
        tags: [ PostgreSQL, setup ]
      