---
# Enable apache2 modules
- name: Enable apache2 modules
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop: "{{ apache2_modules }}"
  notify:
    - Restart Apache
  tags: [ apache2 ]
