---
# setup prerequisites
- name: Install aptitude
  apt: 
    name: aptitude
    update_cache: yes 
    state: latest
  tags: [ prerequisites ]

- name: Add sbt apt key
  apt_key:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823"
    state: present
  tags: [ sbt ]

- name: Add sbt apt repository
  apt_repository:
    repo: "deb https://repo.scala-sbt.org/scalasbt/debian all main"
    state: present
    filename: sbt
    update_cache: yes
  tags: [ sbt ] 


- name: Install prerequisites
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: "{{ prerequisites }}"
  tags: [ prerequisites ]
