---
# Configuration
- name: Create directory
  file:
    path: "{{ config_path }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  tags: [ configuration ]

- name: Configuration
  template: 
    src: "{{ item.path }}"
    dest: "{{ config_path }}/{{ item.name }}"
  loop: "{{ templates }}"
  tags: [ configuration ]

- name: Create symlink
  file: 
    src: "{{ config_path }}/{{ opennsa_service }}"
    dest: /etc/systemd/system/opennsa.service
    state: link 
    owner: root
    group: root
  tags: [ configuration ]

- name: Reload daemon
  systemd: 
    daemon_reload: yes
  tags: [ configuration ]

- name: Start opennsa service
  systemd:
    name: opennsa
    state: started
  tags: [ configuration ]