---
#opennsa.cesnet.cz

# Enviroment
opennsa: "{{ home_path }}/repo"
opennsa_venv: "{{ home_path }}/venv"
python_path: "{{ home_path }}/repo"

# .conf
domain: "nsi.cesnet.cz:2021" #
logfile: "/opt/opennsa/opennsa3.log" # 
host: "opennsa.cesnet.cz"
policy: "allowhairpin" 
nrmmap: "/etc/opennsa/opennsa3-prex.nrm"

# .service
description: "OpenNSA3 node"
after: "syslog.target network.target"
config_file: "{{ config_path }}/opennsa3.conf"
remote_debug: "0"
enviroment_file: "{{ config_path }}/opennsa_environment"
node_file: "{{ config_path }}/opennsa_node.tac"
working_directory: "{{ home_path }}/repo"
restart: "always"
wanted_by: "multi-user.target"
